### ISSUE TITLE
fatal: Remote branch android-12.1 not found in upstream origin

### ISSUE THREAD

**Issue by doncorleone24** [carlodandan/OrangeFox-Action-Builder#7]
It is throwing me this error even though I have the branch.

![image](https://github.com/carlodandan/OrangeFox-Action-Builder/assets/57016517/2d30ead2-f968-45f9-9d5e-e77d9d962ff3)

**Comment by carlodandan** [comment]
You should check the tree if there is really branch named "android-12.1" before posting an issue. I have check some of builder's run, most of them are branch error, really?

**Comment by carlodandan** [comment]
Even your setup manifest part is so messy.
